### ISSUE TITLE
Add bike parking as map data option

### ISSUE THREAD

**Issue by joecaruso** [oaksandspokes/raleighbikeways#40]
It would be nice to have bike parking available as an data/overlay option on the map.  There is some data available in OSM already, but it's far from comprehensive.  Maybe this can be a project for Oaks and Spokes members :) 

https://wiki.openstreetmap.org/wiki/Tag:amenity=bicycle%20parking?uselang=en

Example query:
http://overpass-turbo.eu/s/1prT

**Comment by jonathonwpowell** [comment]
Added!
