### ISSUE TITLE
Change Citrix Cycle to Cardinal Bikeshare

### ISSUE THREAD

**Issue by joecaruso** [oaksandspokes/raleighbikeways#41]
References to Citrix Cycle need to be updated to Cardinal Bikeshare 

https://www.cardinalbikeshare.com/
https://data.raleighnc.gov/datasets/ral::cardinal-cycle-stations/

**Comment by jonathonwpowell** [comment]
Sorry for the long delay, but thank you for reporting it! Fixing in PR #45
